package com.dichotomy.google.auth.entity;

public enum UserInternalMetadata {
    BILLING_ID,
    PASSWORD_RESET_TOKEN,
    PASSWORD_RESET_TOKEN_EXPIRY,
    ACTIVATION_TOKEN,
    ACTIVATION_TOKEN_EXPIRY,
    TWO_FA_TOKEN,
    TWO_FA_TOKEN_EXPIRY,
    ENABLE_TWO_FA_OTP,
    ENABLE_TWO_FA_OTP_EXPIRY,
    API_SECRET_KEY,
    FREE_TRIAL_USED,
    LAST_PASSWORD_UPDATE,
    ACCOUNT_LOCK,
    ACCOUNT_FAILED_ATTEMPT,
    ACCOUNT_LOCKOUT_TIME,
    TOTP_INFO
}
